<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            [
                'brand' => 'Nissan',
                'model' => 'Frontier',
                'year' => 2022,
                'price' => 389000.00,
                'mileage' => 18500,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automática',
                'color' => 'Blanco',
                'description' => 'Nissan Frontier en excelente estado, camioneta doble cabina con equipamiento completo. Cuenta con control de tracción, cámara de reversa, pantalla táctil, conectividad Bluetooth y mucho más. Un solo dueño, mantenimiento al corriente.',
                'featured' => true,
                'status' => 'available',
                'images' => [
                    'https://images.pexels.com/photos/1335077/pexels-photo-1335077.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2519374/pexels-photo-2519374.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/3972755/pexels-photo-3972755.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Corolla',
                'year' => 2021,
                'price' => 285000.00,
                'mileage' => 32000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automática',
                'color' => 'Plata',
                'description' => 'Toyota Corolla sedán en perfectas condiciones. Eficiente en combustible, confiable y con bajo kilometraje. Incluye bolsas de aire, ABS, control de estabilidad, cámara trasera y sistema de navegación.',
                'featured' => true,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
                    'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80',
                    'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Honda',
                'model' => 'CR-V',
                'year' => 2023,
                'price' => 450000.00,
                'mileage' => 8200,
                'fuel_type' => 'Híbrido',
                'transmission' => 'Automática',
                'color' => 'Negro',
                'description' => 'Honda CR-V Híbrido casi nueva, tecnología avanzada de ahorro de combustible. Sistema de frenado automático de emergencia, control de crucero adaptativo, pantalla táctil de 9 pulgadas, Apple CarPlay y Android Auto.',
                'featured' => true,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
                    'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
                    'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Chevrolet',
                'model' => 'Equinox',
                'year' => 2020,
                'price' => 265000.00,
                'mileage' => 54000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automática',
                'color' => 'Rojo',
                'description' => 'Chevrolet Equinox SUV familiar con amplio espacio interior. Motor turbo de 1.5L eficiente, sistema OnStar, pantalla MyLink, sensores de estacionamiento y techo solar panorámico. Ideal para familia.',
                'featured' => true,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
                    'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
                    'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Ford',
                'model' => 'Mustang',
                'year' => 2019,
                'price' => 380000.00,
                'mileage' => 41000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Manual',
                'color' => 'Azul',
                'description' => 'Ford Mustang EcoBoost deportivo en excelente condición. Motor 2.3L turbo de alta performance, escape sport, llantas de aleación, pantalla SYNC 3, sistema de audio premium y modos de manejo seleccionables.',
                'featured' => true,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
                    'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
                    'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Tiguan',
                'year' => 2022,
                'price' => 415000.00,
                'mileage' => 22000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automática',
                'color' => 'Gris',
                'description' => 'Volkswagen Tiguan Comfortline en impecable estado. SUV alemán con excelente calidad de construcción, interior de cuero, sistema de infoentretenimiento con pantalla táctil, climatización automática dual y asistente de estacionamiento.',
                'featured' => true,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
                    'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80',
                    'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Nissan',
                'model' => 'Sentra',
                'year' => 2021,
                'price' => 210000.00,
                'mileage' => 38000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automática',
                'color' => 'Blanco',
                'description' => 'Nissan Sentra sedán económico y confiable. Motor 2.0L de bajo consumo, pantalla táctil de 8 pulgadas, Apple CarPlay, Android Auto, sensores de reversa y cámara trasera. Perfecto para uso diario en ciudad.',
                'featured' => false,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80',
                    'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Toyota',
                'model' => 'RAV4',
                'year' => 2020,
                'price' => 340000.00,
                'mileage' => 47000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automática',
                'color' => 'Plateado',
                'description' => 'Toyota RAV4 SUV robusto y confiable. Reconocida confiabilidad Toyota, tracción en las 4 ruedas, sistema multimedia Toyota, pantalla táctil, seguridad Toyota Safety Sense con frenado automático de emergencia.',
                'featured' => false,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
                    'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Honda',
                'model' => 'Civic',
                'year' => 2018,
                'price' => 180000.00,
                'mileage' => 75000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Manual',
                'color' => 'Azul',
                'description' => 'Honda Civic deportivo en buenas condiciones. Motor VTEC confiable, estilo deportivo tipo sedan, sistema de audio con conectividad Bluetooth, aire acondicionado automático y control de crucero.',
                'featured' => false,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
                    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Chevrolet',
                'model' => 'Traverse',
                'year' => 2019,
                'price' => 295000.00,
                'mileage' => 62000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automática',
                'color' => 'Blanco',
                'description' => 'Chevrolet Traverse SUV de 3 filas para familia grande. Amplio espacio para 8 pasajeros, motor V6 potente, sistema OnStar, pantalla MyLink de 8 pulgadas, cámara surround view y asientos de cuero.',
                'featured' => false,
                'status' => 'available',
                'images' => [
                    'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
                    'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
                ],
            ],
            [
                'brand' => 'Ford',
                'model' => 'Ranger',
                'year' => 2021,
                'price' => 365000.00,
                'mileage' => 28000,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automática',
                'color' => 'Negro',
                'description' => 'Ford Ranger XLT Diesel en excelente estado. Camioneta pick-up de trabajo y aventura, motor 2.0L diesel biturbo eficiente, tracción 4x4, caja de carga con liner, sistema SYNC 3 y cámara trasera.',
                'featured' => false,
                'status' => 'available',
                'images' => [
                    'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/244206/pexels-photo-244206.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2519374/pexels-photo-2519374.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Jetta',
                'year' => 2023,
                'price' => 320000.00,
                'mileage' => 11000,
                'fuel_type' => 'Gasolina',
                'transmission' => 'Automática',
                'color' => 'Gris',
                'description' => 'Volkswagen Jetta Highline casi nuevo, el sedán europeo por excelencia. Motor TSI turbo eficiente, interior premium con tapicería de cuero, pantalla táctil con App-Connect, climatización dual y faros LED.',
                'featured' => false,
                'status' => 'sold',
                'images' => [
                    'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
                    'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80',
                    'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80',
                ],
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }
}
